##########################################################
#                    PlayerVaults Config                   #
#  To give a user access to a player vault give them the following permission:
#  - playervaults.limit.10
#  - playervaults.limit.* for unlimited vaults
#
#  Admin perms:
#  - playervaults.admin.*
#  - playervaults.admin.open
#  - playervaults.admin.alter
#  - playervaults.admin.clear
#  - playervaults.admin.reload
#
##########################################################

# available types:
#  - flat
#  - mysql
#
# WARNING: changing storage type does not transfer data between the two databases. All data will be lost.
storageType: "flat"

#Database info (mysql)
host: "host"
port: 3306
database: "playervaults"
user: "user"
pass: "pass"

# message prefix
prefix: "&1[&bPlayerVaults&1] "

#messages:
noVaults: "&c&lSorry! it seems that you dont have access to that"
vaultLimitReached: "&c&lYou are limited to &f&l%vault_limit% &c&lvaults!"
inUse: "&c&lPlease wait the playervault is currently in use by an administrator."
#menu
menuName: "&f&lPlayer vault &c&l(&f&l%vault_number%&c&l)"
backButtonName: "&fBack to previous page"
backButtonDescription:
  - "&bClick me to get back"
  - "&bto the previous page"
nextButtonName: "&fNext page"
nextButtonDescription:
  - "&bClick me to get"
  - "&bto the next page"